api_platform:
    title: 'Technical Test - Tickets System'
    description: 'This is the API for managing tickets, events and organisers.'
    version: '1.0.0'
    formats:
        json:
            mime_types: ['application/json']
        jsonld: 
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
    exception_to_status:
        App\Exception\ForbiddenException: 403
        App\Exception\NotFoundException: 404
        App\Exception\UnauthorizedException: 401
        App\Exception\InvalidInputException: 400
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
